export const RISU_APP_INTERNAL_DRAG_TYPE = 'application/x-risu-app-internal-drag'
export const RISU_EFFECT_DRAG_TYPE = 'application/x-risu-effect-drag'
export const RISU_PRESET_DRAG_TYPE = 'application/x-risu-preset-drag'
export const RISU_PROMPT_DRAG_TYPE = 'application/x-risu-prompt-drag'
export const RISU_SIDEBAR_DRAG_TYPE = 'application/x-risu-sidebar-drag'
export const RISU_TRIGGER_DRAG_TYPE = 'application/x-risu-trigger-drag'
